x-default-environment: &default-environment
  TZ: "UTC"

services:
  app:
    TODO

  db:
    TODO

  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - 9999:8080
    environment:
      PLANTUML_LIMIT_SIZE: 8192
    profiles:
      - design

volumes:
  db_data:
